# Adiciona Caminhao
POST http://localhost:8080/auth/register
Content-type: application/json

{
  "name": "example",
  "email": "example@gmail.com",
  "password": "Senha123"
}

###
POST http://localhost:8080/auth/login
Content-type: application/json

{
  "email": "example@gmail.com",
  "password": "Senha123"
}

###
GET http://localhost:8080/user
Authorization: Bearer TOKEN_AQUI
